obsidian:
  vault: C:\Users\jmciges\OneDrive - Seresco, S.A\Documentos\Marques-de-Valdecilla

# Task properties fields names in Obsidian
tasks:
  properties:
    end_date: "fecha_realizacion"
    update: "updated"
    state: "estado"  
    next_step: "proximo_paso"
    next_date: "proxima_fecha"
  paths:
    resolved: "TAREAS/Completadas/Tickets/resueltos"
    closed: "TAREAS/Completadas/Tickets/cerrados"
    team:
      resolved: "REVISIÃ“N DE TICKETS/Resueltos"
      closed: "REVISIÃ“N DE TICKETS/Cerrados"
  states:
    resolved: "âœ”ï¸"
    closed: "ğŸ”’"
    waiting: "â³"